[metadata]
name = mpl_cn_font
version = 0.1.0
description = A Python package to configure Matplotlib to display Chinese fonts.
author = Zongwu Wang
author_email = wangzongwu@sjtu.edu.cn
url = https://github.com/ZongwuWang/mpl_cn_font
license = MIT

[options]
packages = find:
package_dir =
    = src
install_requires =
    matplotlib

[options.packages.find]
where = src

[options.package_data]
mpl_cn_font = 
    fonts/*.ttf

[options.extras_require]
dev =
    setuptools
    wheel
    twine